In [1]:
import xarray as xr
from pocean.dsg import CfDsgAccessor, open_cfdsg_dataframe, IncompleteMultidimensionalProfile

In [2]:
fn = 'pocean/tests/dsg/profile/resources/om-1dy11.nc'
xds = xr.open_dataset(fn)
ds = xds.to_dataframe()

In [3]:
ds

                    conductivity         crs  \
profile z
10_2    0.990000       27.608490 -2147483647
        1.980000       29.105530 -2147483647
        2.970000       26.596979 -2147483647
        3.960000       26.323580 -2147483647
        4.950000       25.597185 -2147483647
        4.960000             NaN -2147483647
        5.940000       25.735382 -2147483647
        5.950000             NaN -2147483647
        6.930000       26.151882 -2147483647
        6.940000             NaN -2147483647
        7.920000       25.816408 -2147483647
        7.930000             NaN -2147483647
        8.910000       27.185120 -2147483647
        8.920000             NaN -2147483647
        9.910000       27.015156 -2147483647
        10.900000      25.633535 -2147483647
        11.890000      27.139164 -2147483647
        12.880000      26.170244 -2147483647
        13.870000      25.562387 -2147483647
        14.860000      26.031151 -2147483647
        14.870000            NaN -2147483647
        15.850000      25.540108 -2147483647
        15.860000            NaN -2147483647
        16.840000      25.154594 -2147483647
        16.850000            NaN -2147483647
        17.830000      25.209305 -2147483647
        17.840000            NaN -2147483647
        18.820000      24.958042 -2147483647
        18.830000            NaN -2147483647
        19.809999      24.957897 -2147483647
...                          ...         ...
9_2     127.800003           NaN -2147483647
        128.789993           NaN -2147483647
        129.779999           NaN -2147483647
        130.779999           NaN -2147483647
        131.770004           NaN -2147483647
        132.759995           NaN -2147483647
        133.750000           NaN -2147483647
        134.740005           NaN -2147483647
        135.729996           NaN -2147483647
        136.720001           NaN -2147483647
        137.710007           NaN -2147483647
        138.699997           NaN -2147483647
        139.690002           NaN -2147483647
        140.679993           NaN -2147483647
        141.669998           NaN -2147483647
        142.660004           NaN -2147483647
        143.649994           NaN -2147483647
        144.639999           NaN -2147483647
        145.630005           NaN -2147483647
        146.619995           NaN -2147483647
        147.610001           NaN -2147483647
        148.600006           NaN -2147483647
        149.589996           NaN -2147483647
        150.580002           NaN -2147483647
        151.570007           NaN -2147483647
        152.559998           NaN -2147483647
        153.550003           NaN -2147483647
        154.539993           NaN -2147483647
        155.529999           NaN -2147483647
        156.520004           NaN -2147483647

                                                       file  flag   grid  \
profile z
10_2    0.990000    G:\SeaCatData\Processed\1DY11\BON004.up     0  70M38
        1.980000    G:\SeaCatData\Processed\1DY11\BON004.up     0  70M38
        2.970000    G:\SeaCatData\Processed\1DY11\BON004.up     0  70M38
        3.960000    G:\SeaCatData\Processed\1DY11\BON004.up     0  70M38
        4.950000    G:\SeaCatData\Processed\1DY11\BON004.up     0  70M38
        4.960000    G:\SeaCatData\Processed\1DY11\BON004.up     0  70M38
        5.940000    G:\SeaCatData\Processed\1DY11\BON004.up     0  70M38
        5.950000    G:\SeaCatData\Processed\1DY11\BON004.up     0  70M38
        6.930000    G:\SeaCatData\Processed\1DY11\BON004.up     0  70M38
        6.940000    G:\SeaCatData\Processed\1DY11\BON004.up     0  70M38
        7.920000    G:\SeaCatData\Processed\1DY11\BON004.up     0  70M38
        7.930000    G:\SeaCatData\Processed\1DY11\BON004.up     0  70M38
        8.910000    G:\SeaCatData\Processed\1DY11\BON004.up     0  70M38
        8.920000    G:\SeaCatData\Processed\1DY11\BON004.up     0  70M38
        9.910000    G:\SeaCatData\Processed\1DY11\BON004.up     0  70M38
        10.900000   G:\SeaCatData\Processed\1DY11\BON004.up     0  70M38
        11.890000   G:\SeaCatData\Processed\1DY11\BON004.up     0  70M38
        12.880000   G:\SeaCatData\Processed\1DY11\BON004.up     0  70M38
        13.870000   G:\SeaCatData\Processed\1DY11\BON004.up     0  70M38
        14.860000   G:\SeaCatData\Processed\1DY11\BON004.up     0  70M38
        14.870000   G:\SeaCatData\Processed\1DY11\BON004.up     0  70M38
        15.850000   G:\SeaCatData\Processed\1DY11\BON004.up     0  70M38
        15.860000   G:\SeaCatData\Processed\1DY11\BON004.up     0  70M38
        16.840000   G:\SeaCatData\Processed\1DY11\BON004.up     0  70M38
        16.850000   G:\SeaCatData\Processed\1DY11\BON004.up     0  70M38
        17.830000   G:\SeaCatData\Processed\1DY11\BON004.up     0  70M38
        17.840000   G:\SeaCatData\Processed\1DY11\BON004.up     0  70M38
        18.820000   G:\SeaCatData\Processed\1DY11\BON004.up     0  70M38
        18.830000   G:\SeaCatData\Processed\1DY11\BON004.up     0  70M38
        19.809999   G:\SeaCatData\Processed\1DY11\BON004.up     0  70M38
...                                                     ...   ...    ...
9_2     127.800003  G:\SeaCatData\Processed\1DY11\BON003.up     0  70M39
        128.789993  G:\SeaCatData\Processed\1DY11\BON003.up     0  70M39
        129.779999  G:\SeaCatData\Processed\1DY11\BON003.up     0  70M39
        130.779999  G:\SeaCatData\Processed\1DY11\BON003.up     0  70M39
        131.770004  G:\SeaCatData\Processed\1DY11\BON003.up     0  70M39
        132.759995  G:\SeaCatData\Processed\1DY11\BON003.up     0  70M39
        133.750000  G:\SeaCatData\Processed\1DY11\BON003.up     0  70M39
        134.740005  G:\SeaCatData\Processed\1DY11\BON003.up     0  70M39
        135.729996  G:\SeaCatData\Processed\1DY11\BON003.up     0  70M39
        136.720001  G:\SeaCatData\Processed\1DY11\BON003.up     0  70M39
        137.710007  G:\SeaCatData\Processed\1DY11\BON003.up     0  70M39
        138.699997  G:\SeaCatData\Processed\1DY11\BON003.up     0  70M39
        139.690002  G:\SeaCatData\Processed\1DY11\BON003.up     0  70M39
        140.679993  G:\SeaCatData\Processed\1DY11\BON003.up     0  70M39
        141.669998  G:\SeaCatData\Processed\1DY11\BON003.up     0  70M39
        142.660004  G:\SeaCatData\Processed\1DY11\BON003.up     0  70M39
        143.649994  G:\SeaCatData\Processed\1DY11\BON003.up     0  70M39
        144.639999  G:\SeaCatData\Processed\1DY11\BON003.up     0  70M39
        145.630005  G:\SeaCatData\Processed\1DY11\BON003.up     0  70M39
        146.619995  G:\SeaCatData\Processed\1DY11\BON003.up     0  70M39
        147.610001  G:\SeaCatData\Processed\1DY11\BON003.up     0  70M39
        148.600006  G:\SeaCatData\Processed\1DY11\BON003.up     0  70M39
        149.589996  G:\SeaCatData\Processed\1DY11\BON003.up     0  70M39
        150.580002  G:\SeaCatData\Processed\1DY11\BON003.up     0  70M39
        151.570007  G:\SeaCatData\Processed\1DY11\BON003.up     0  70M39
        152.559998  G:\SeaCatData\Processed\1DY11\BON003.up     0  70M39
        153.550003  G:\SeaCatData\Processed\1DY11\BON003.up     0  70M39
        154.539993  G:\SeaCatData\Processed\1DY11\BON003.up     0  70M39
        155.529999  G:\SeaCatData\Processed\1DY11\BON003.up     0  70M39
        156.520004  G:\SeaCatData\Processed\1DY11\BON003.up     0  70M39

                    haul   latitude   longitude  pressure   salinity  \
profile z
10_2    0.990000       2  60.083000 -172.007996       1.0  30.734600
        1.980000       2  60.083000 -172.007996       2.0  30.762800
        2.970000       2  60.083000 -172.007996       3.0  30.764601
        3.960000       2  60.083000 -172.007996       4.0  30.766701
        4.950000       2  60.083000 -172.007996       5.0  30.770399
        4.960000       2  60.083000 -172.007996       NaN        NaN
        5.940000       2  60.083000 -172.007996       6.0  30.782801
        5.950000       2  60.083000 -172.007996       NaN        NaN
        6.930000       2  60.083000 -172.007996       7.0  30.795401
        6.940000       2  60.083000 -172.007996       NaN        NaN
        7.920000       2  60.083000 -172.007996       8.0  30.803200
        7.930000       2  60.083000 -172.007996       NaN        NaN
        8.910000       2  60.083000 -172.007996       9.0  30.789600
        8.920000       2  60.083000 -172.007996       NaN        NaN
        9.910000       2  60.083000 -172.007996      10.0  30.793600
        10.900000      2  60.083000 -172.007996      11.0  30.787500
        11.890000      2  60.083000 -172.007996      12.0  30.795799
        12.880000      2  60.083000 -172.007996      13.0  30.915501
        13.870000      2  60.083000 -172.007996      14.0  31.115400
        14.860000      2  60.083000 -172.007996      15.0  31.249901
        14.870000      2  60.083000 -172.007996       NaN        NaN
        15.850000      2  60.083000 -172.007996      16.0  31.295000
        15.860000      2  60.083000 -172.007996       NaN        NaN
        16.840000      2  60.083000 -172.007996      17.0  31.313299
        16.850000      2  60.083000 -172.007996       NaN        NaN
        17.830000      2  60.083000 -172.007996      18.0  31.325500
        17.840000      2  60.083000 -172.007996       NaN        NaN
        18.820000      2  60.083000 -172.007996      19.0  31.334400
        18.830000      2  60.083000 -172.007996       NaN        NaN
        19.809999      2  60.083000 -172.007996      20.0  31.344900
...                  ...        ...         ...       ...        ...
9_2     127.800003     2  59.903999 -172.169006       NaN        NaN
        128.789993     2  59.903999 -172.169006       NaN        NaN
        129.779999     2  59.903999 -172.169006       NaN        NaN
        130.779999     2  59.903999 -172.169006       NaN        NaN
        131.770004     2  59.903999 -172.169006       NaN        NaN
        132.759995     2  59.903999 -172.169006       NaN        NaN
        133.750000     2  59.903999 -172.169006       NaN        NaN
        134.740005     2  59.903999 -172.169006       NaN        NaN
        135.729996     2  59.903999 -172.169006       NaN        NaN
        136.720001     2  59.903999 -172.169006       NaN        NaN
        137.710007     2  59.903999 -172.169006       NaN        NaN
        138.699997     2  59.903999 -172.169006       NaN        NaN
        139.690002     2  59.903999 -172.169006       NaN        NaN
        140.679993     2  59.903999 -172.169006       NaN        NaN
        141.669998     2  59.903999 -172.169006       NaN        NaN
        142.660004     2  59.903999 -172.169006       NaN        NaN
        143.649994     2  59.903999 -172.169006       NaN        NaN
        144.639999     2  59.903999 -172.169006       NaN        NaN
        145.630005     2  59.903999 -172.169006       NaN        NaN
        146.619995     2  59.903999 -172.169006       NaN        NaN
        147.610001     2  59.903999 -172.169006       NaN        NaN
        148.600006     2  59.903999 -172.169006       NaN        NaN
        149.589996     2  59.903999 -172.169006       NaN        NaN
        150.580002     2  59.903999 -172.169006       NaN        NaN
        151.570007     2  59.903999 -172.169006       NaN        NaN
        152.559998     2  59.903999 -172.169006       NaN        NaN
        153.550003     2  59.903999 -172.169006       NaN        NaN
        154.539993     2  59.903999 -172.169006       NaN        NaN
        155.529999     2  59.903999 -172.169006       NaN        NaN
        156.520004     2  59.903999 -172.169006       NaN        NaN

                      sigma_t  temperature                time
profile z
10_2    0.990000    24.673401       1.4637 2011-05-21 12:33:00
        1.980000    24.696699       3.0878 2011-05-21 12:33:00
        2.970000    24.698799       0.2917 2011-05-21 12:33:00
        3.960000    24.701900       0.2646 2011-05-21 12:33:00
        4.950000    24.705700      -0.7847 2011-05-21 12:33:00
        4.960000          NaN          NaN 2011-05-21 12:33:00
        5.940000    24.716999      -0.6478 2011-05-21 12:33:00
        5.950000          NaN          NaN 2011-05-21 12:33:00
        6.930000    24.728001      -0.3618 2011-05-21 12:33:00
        6.940000          NaN          NaN 2011-05-21 12:33:00
        7.920000    24.734699      -0.5882 2011-05-21 12:33:00
        7.930000          NaN          NaN 2011-05-21 12:33:00
        8.910000    24.722900       0.5176 2011-05-21 12:33:00
        8.920000          NaN          NaN 2011-05-21 12:33:00
        9.910000    24.726500       0.8539 2011-05-21 12:33:00
        10.900000   24.721201      -0.8273 2011-05-21 12:33:00
        11.890000   24.728800       0.7963 2011-05-21 12:33:00
        12.880000   24.834900      -0.1131 2011-05-21 12:33:00
        13.870000   25.009600      -0.9131 2011-05-21 12:33:00
        14.860000   25.125000      -0.2996 2011-05-21 12:33:00
        14.870000         NaN          NaN 2011-05-21 12:33:00
        15.850000   25.163401      -0.9162 2011-05-21 12:33:00
        15.860000         NaN          NaN 2011-05-21 12:33:00
        16.840000   25.178801      -1.3870 2011-05-21 12:33:00
        16.850000         NaN          NaN 2011-05-21 12:33:00
        17.830000   25.189100      -1.2654 2011-05-21 12:33:00
        17.840000         NaN          NaN 2011-05-21 12:33:00
        18.820000   25.196600      -1.6102 2011-05-21 12:33:00
        18.830000         NaN          NaN 2011-05-21 12:33:00
        19.809999   25.205400      -1.6136 2011-05-21 12:33:00
...                       ...          ...                 ...
9_2     127.800003        NaN          NaN 2011-05-21 10:45:00
        128.789993        NaN          NaN 2011-05-21 10:45:00
        129.779999        NaN          NaN 2011-05-21 10:45:00
        130.779999        NaN          NaN 2011-05-21 10:45:00
        131.770004        NaN          NaN 2011-05-21 10:45:00
        132.759995        NaN          NaN 2011-05-21 10:45:00
        133.750000        NaN          NaN 2011-05-21 10:45:00
        134.740005        NaN          NaN 2011-05-21 10:45:00
        135.729996        NaN          NaN 2011-05-21 10:45:00
        136.720001        NaN          NaN 2011-05-21 10:45:00
        137.710007        NaN          NaN 2011-05-21 10:45:00
        138.699997        NaN          NaN 2011-05-21 10:45:00
        139.690002        NaN          NaN 2011-05-21 10:45:00
        140.679993        NaN          NaN 2011-05-21 10:45:00
        141.669998        NaN          NaN 2011-05-21 10:45:00
        142.660004        NaN          NaN 2011-05-21 10:45:00
        143.649994        NaN          NaN 2011-05-21 10:45:00
        144.639999        NaN          NaN 2011-05-21 10:45:00
        145.630005        NaN          NaN 2011-05-21 10:45:00
        146.619995        NaN          NaN 2011-05-21 10:45:00
        147.610001        NaN          NaN 2011-05-21 10:45:00
        148.600006        NaN          NaN 2011-05-21 10:45:00
        149.589996        NaN          NaN 2011-05-21 10:45:00
        150.580002        NaN          NaN 2011-05-21 10:45:00
        151.570007        NaN          NaN 2011-05-21 10:45:00
        152.559998        NaN          NaN 2011-05-21 10:45:00
        153.550003        NaN          NaN 2011-05-21 10:45:00
        154.539993        NaN          NaN 2011-05-21 10:45:00
        155.529999        NaN          NaN 2011-05-21 10:45:00
        156.520004        NaN          NaN 2011-05-21 10:45:00

[9590 rows x 13 columns]

In [4]:
x = open_cfdsg_dataframe(ds, klass=IncompleteMultidimensionalProfile)
x

<xarray.Dataset>
Dimensions:       (profile: 35, z: 274)
Coordinates:
  * profile       (profile) object '10_2' '11_5' '12_2' '13_2' '15_2' '17_2' ...
  * z             (z) float64 0.99 1.98 2.97 3.96 4.95 4.96 5.94 5.95 6.93 ...
    latitude      (profile, z) float64 60.08 60.08 60.08 60.08 60.08 60.08 ...
    longitude     (profile, z) float64 -172.0 -172.0 -172.0 -172.0 -172.0 ...
    time          (profile, z) datetime64[ns] 2011-05-21T12:33:00 ...
Data variables:
    conductivity  (profile, z) float64 27.61 29.11 26.6 26.32 25.6 nan 25.74 ...
    crs           (profile, z) int64 -2147483647 -2147483647 -2147483647 ...
    file          (profile, z) object 'G:\\SeaCatData\\Processed\\1DY11\\BON004.up' ...
    flag          (profile, z) int32 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
    grid          (profile, z) object '70M38' '70M38' '70M38' '70M38' ...
    haul          (profile, z) int32 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 ...
    pressure      (profile, z) float64 1.0 2.0 3.0 4.0 5.0 nan 6.0 nan 7.0 ...
    salinity      (profile, z) float64 30.73 30.76 30.76 30.77 30.77 nan ...
    sigma_t       (profile, z) float64 24.67 24.7 24.7 24.7 24.71 nan 24.72 ...
    temperature   (profile, z) float64 1.464 3.088 0.2917 0.2646 -0.7847 nan ...

In [5]:
x.cfdsg.reduce({
    'crs': (),
    'file': ('profile',),
    'flag': ('profile',),
    'grid': ('profile',),
    'haul': ('profile',)
})
x

<xarray.Dataset>
Dimensions:       (profile: 35, z: 274)
Coordinates:
  * profile       (profile) object '10_2' '11_5' '12_2' '13_2' '15_2' '17_2' ...
  * z             (z) float64 0.99 1.98 2.97 3.96 4.95 4.96 5.94 5.95 6.93 ...
    latitude      (profile) float64 60.08 59.91 59.9 59.7 59.61 59.34 59.11 ...
    longitude     (profile) float64 -172.0 -171.7 -171.3 -171.5 -170.9 ...
    time          (profile) datetime64[ns] 2011-05-21T12:33:00 ...
Data variables:
    conductivity  (profile, z) float64 27.61 29.11 26.6 26.32 25.6 nan 25.74 ...
    crs           int64 -2147483647
    file          (profile) object 'G:\\SeaCatData\\Processed\\1DY11\\BON004.up' ...
    flag          (profile) int32 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
    grid          (profile) object '70M38' '70M38' 'M5E' 'M5S' '70M35' ...
    haul          (profile) int32 2 5 2 2 2 2 2 3 2 2 2 2 2 2 2 3 5 2 2 2 2 ...
    pressure      (profile, z) float64 1.0 2.0 3.0 4.0 5.0 nan 6.0 nan 7.0 ...
    salinity      (profile, z) float64 30.73 30.76 30.76 30.77 30.77 nan ...
    sigma_t       (profile, z) float64 24.67 24.7 24.7 24.7 24.71 nan 24.72 ...
    temperature   (profile, z) float64 1.464 3.088 0.2917 0.2646 -0.7847 nan ...

In [6]:
x.cfdsg.update_attrs()
x

<xarray.Dataset>
Dimensions:       (profile: 35, z: 274)
Coordinates:
  * profile       (profile) object '10_2' '11_5' '12_2' '13_2' '15_2' '17_2' ...
  * z             (z) float64 0.99 1.98 2.97 3.96 4.95 4.96 5.94 5.95 6.93 ...
    latitude      (profile) float64 60.08 59.91 59.9 59.7 59.61 59.34 59.11 ...
    longitude     (profile) float64 -172.0 -171.7 -171.3 -171.5 -170.9 ...
    time          (profile) datetime64[ns] 2011-05-21T12:33:00 ...
Data variables:
    conductivity  (profile, z) float64 27.61 29.11 26.6 26.32 25.6 nan 25.74 ...
    crs           int64 -2147483647
    file          (profile) object 'G:\\SeaCatData\\Processed\\1DY11\\BON004.up' ...
    flag          (profile) int32 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
    grid          (profile) object '70M38' '70M38' 'M5E' 'M5S' '70M35' ...
    haul          (profile) int32 2 5 2 2 2 2 2 3 2 2 2 2 2 2 2 3 5 2 2 2 2 ...
    pressure      (profile, z) float64 1.0 2.0 3.0 4.0 5.0 nan 6.0 nan 7.0 ...
    salinity      (profile, z) float64 30.73 30.76 30.76 30.77 30.77 nan ...
    sigma_t       (profile, z) float64 24.67 24.7 24.7 24.7 24.71 nan 24.72 ...
    temperature   (profile, z) float64 1.464 3.088 0.2917 0.2646 -0.7847 nan ...
Attributes:
    Conventions:    CF-1.6
    featureType:    profile
    cdm_data_type:  Profile

In [7]:
x.to_netcdf('imp.nc')